services:
  traefik:
    image: traefik:v3.5
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik-dynamic:/etc/traefik/dynamic:ro
    networks:
      - provisioned-apps

  api:
    environment:
      PROVISIONER_BACKEND: docker
      DOCKER_NETWORK_NAME: tiny-provisioner-apps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    environment:
      PROVISIONER_BACKEND: docker
      DOCKER_NETWORK_NAME: tiny-provisioner-apps
      TRAEFIK_DYNAMIC_CONFIG_PATH: /var/lib/tiny-provisioner/traefik/apps.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-dynamic:/var/lib/tiny-provisioner/traefik

  tiny-python-http-app:
    build: ./provisioned_templates/tiny-python-http-app
    image: tiny-python-http-app:local
    profiles:
      - templates

volumes:
  traefik-dynamic:

networks:
  provisioned-apps:
    name: tiny-provisioner-apps
